# Generated by Django 3.2.3 on 2021-05-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0009_auto_20210529_2345'),
        ('geo', '0006_auto_20210512_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range_from', models.FloatField()),
                ('range_to', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('type', models.CharField(choices=[('MASS', 'MASS'), ('SIZE', 'SIZE'), ('LDM', 'LDM')], max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='geo.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range_from', models.FloatField()),
                ('range_to', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('type', models.CharField(choices=[('MASS', 'MASS'), ('SIZE', 'SIZE'), ('LDM', 'LDM')], max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='route.hubroute')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
