# Generated by Django 3.2.3 on 2021-06-26 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0015_alter_routetimetable_weekdays'),
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRanked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range_from', models.FloatField()),
                ('range_to', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('name', models.CharField(max_length=120)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranked_services', to='route.hubroute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_services', to='route.hubroute')),
            ],
        ),
    ]
