# Generated by Django 3.2.3 on 2021-06-26 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_serviceadditional_serviceranked'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceadditional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
