# Generated by Django 3.2.3 on 2021-07-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_city_types'),
        ('pricing', '0005_serviceranked_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonePricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimal_distance', models.IntegerField()),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_info', to='geo.zone')),
            ],
        ),
    ]
