# Generated by Django 3.2.3 on 2021-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_zonepricinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zonepricinginfo',
            name='minimal_distance',
            field=models.IntegerField(default=0),
        ),
    ]
