# Generated by Django 3.2.3 on 2021-08-07 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0006_zonepricinginfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonepricinginfo',
            name='minimal_distance',
        ),
        migrations.AddField(
            model_name='zonepricinginfo',
            name='minimal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
