# Generated by Django 3.2.3 on 2021-09-15 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0007_zonepricinginfo_markup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonepricinginfo',
            name='minimal_price',
        ),
        migrations.AddField(
            model_name='routerate',
            name='minimal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='zonerate',
            name='minimal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
