# Generated by Django 3.2.2 on 2021-05-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0006_auto_20210512_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR')], default='TRUCK', max_length=20)),
                ('distance', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_routes_as_destination', to='geo.city')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_routes_as_source', to='geo.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RouteRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range_from', models.FloatField()),
                ('range_to', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('unit_type', models.CharField(choices=[('KILOGRAM', 'kg'), ('CUBIC_METER', 'm3'), ('LDM', 'ldm')], max_length=20)),
                ('type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR')], max_length=20)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='route.hubroute')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('range_from', models.FloatField()),
                ('range_to', models.FloatField()),
                ('price_per_unit', models.DecimalField(decimal_places=8, max_digits=20)),
                ('currency', models.CharField(default='EUR', max_length=12)),
                ('unit_type', models.CharField(choices=[('KILOGRAM', 'kg'), ('CUBIC_METER', 'm3'), ('LDM', 'ldm')], max_length=20)),
                ('type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR')], max_length=20)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='geo.zone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hub_routes', models.ManyToManyField(related_name='paths', to='route.HubRoute')),
            ],
        ),
        migrations.CreateModel(
            name='AuxiliaryRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR')], default='TRUCK', max_length=20)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_routes_as_destination', to='geo.city')),
                ('path', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_routes', to='route.path')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auxiliary_routes_as_source', to='geo.city')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
