# Generated by Django 3.2.2 on 2021-05-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_auto_20210521_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routerate',
            name='type',
            field=models.CharField(choices=[('MASS', 'MASS'), ('SIZE', 'SIZE'), ('LDM', 'LDM')], max_length=20),
        ),
        migrations.AlterField(
            model_name='zonerate',
            name='type',
            field=models.CharField(choices=[('MASS', 'MASS'), ('SIZE', 'SIZE'), ('LDM', 'LDM')], max_length=20),
        ),
    ]
