# Generated by Django 3.2.2 on 2021-05-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_auto_20210521_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routerate',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='zonerate',
            name='unit_type',
        ),
    ]
