# Generated by Django 3.2.2 on 2021-05-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0007_auto_20210521_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
