# Generated by Django 3.2.3 on 2021-05-29 20:45

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0008_alter_path_total_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=7)),
            ],
        ),
        migrations.RemoveField(
            model_name='zonerate',
            name='zone',
        ),
        migrations.DeleteModel(
            name='RouteRate',
        ),
        migrations.DeleteModel(
            name='ZoneRate',
        ),
    ]
