# Generated by Django 3.2.3 on 2021-05-29 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0011_alter_routetimetable_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubroute',
            name='timetable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.routetimetable'),
        ),
    ]
