# Generated by Django 3.2.3 on 2021-05-29 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0012_hubroute_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubroute',
            name='timetable',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='route.routetimetable'),
        ),
    ]
