# Generated by Django 3.2.3 on 2021-06-26 17:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0014_alter_routetimetable_weekdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routetimetable',
            name='weekdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=7),
        ),
    ]
