# Generated by Django 3.2.3 on 2021-06-30 12:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20210512_1932'),
        ('route', '0015_alter_routetimetable_weekdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteInPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('TRUCK', 'TRUCK'), ('TRAIN', 'TRAIN'), ('AIR', 'AIR')], default='TRUCK', max_length=20)),
                ('_distance', models.IntegerField(null=True)),
                ('_duration', models.IntegerField(null=True)),
                ('is_hub', models.BooleanField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_routes_as_destination', to='geo.city')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelManagers(
            name='path',
            managers=[
                ('creatable', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='path',
            name='hub_routes',
        ),
        migrations.DeleteModel(
            name='AuxiliaryRoute',
        ),
        migrations.AddField(
            model_name='routeinpath',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path_routes', to='route.path'),
        ),
        migrations.AddField(
            model_name='routeinpath',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_routes_as_source', to='geo.city'),
        ),
    ]
