# Generated by Django 3.2.3 on 2021-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0017_alter_routeinpath_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='total_duration',
        ),
        migrations.AddField(
            model_name='path',
            name='total_duration_max',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='path',
            name='total_duration_min',
            field=models.IntegerField(default=0),
        ),
    ]
