# Generated by Django 3.2.3 on 2021-07-22 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0018_auto_20210630_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubroute',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hubroute',
            name='duration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='path',
            name='total_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='total_duration_max',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='path',
            name='total_duration_min',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='routeinpath',
            name='_distance',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='routeinpath',
            name='_duration',
            field=models.FloatField(null=True),
        ),
    ]
