# Generated by Django 3.2.3 on 2021-08-21 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0021_auto_20210808_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubroute',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hubroute',
            name='rates_valid_to',
            field=models.DateField(default=datetime.date(9999, 12, 31), null=True),
        ),
        migrations.AddField(
            model_name='hubroute',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
