# Generated by Django 3.2.3 on 2021-08-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0023_routeinpath_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubroute',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
