# Generated by Django 3.2.3 on 2021-08-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0024_hubroute_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubroute',
            name='destination_is_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hubroute',
            name='source_is_storage',
            field=models.BooleanField(default=False),
        ),
    ]
