# Generated by Django 3.2.3 on 2021-08-28 10:55

from django.db import migrations

from utils.enums import RouteType


def update_storage(apps, schema_editor):
    HubRoute = apps.get_model('route', 'HubRoute')

    HubRoute.objects.filter(type=RouteType.TRUCK.value).update(source_is_storage=True, destination_is_storage=True)


class Migration(migrations.Migration):
    dependencies = [
        ('route', '0025_auto_20210828_1052'),
    ]

    operations = [
    ]
