# Generated by Django 3.2.3 on 2021-09-15 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0028_auto_20210913_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hubroute',
            name='minimal_price',
        ),
    ]
