# Generated by Django 3.2.3 on 2021-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0029_remove_hubroute_minimal_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='optimal',
            field=models.BooleanField(default=False),
        ),
    ]
