# Generated by Django 3.2.2 on 2021-05-19 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_size', models.FloatField()),
                ('total_ldm', models.FloatField()),
                ('total_mass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMALL', "20'"), ('MIDDLE', "40'"), ('BIG', "40'HC"), ('LARGE', "45'HC")], default="20'", max_length=40)),
                ('amount', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='goods.good')),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('mass', models.FloatField()),
                ('type', models.CharField(choices=[('BOX', 'BOX'), ('PALLET', 'PELLET')], default='BOX', max_length=20)),
                ('amount', models.IntegerField()),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='goods.good')),
            ],
        ),
    ]
