# Generated by Django 3.2.2 on 2021-05-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='total_size',
            new_name='total_volume',
        ),
    ]
