# Generated by Django 3.2.3 on 2021-06-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_total_size_good_total_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='total_ldm',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='total_mass',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='good',
            name='total_volume',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
