# Generated by Django 3.2.3 on 2021-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20210628_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='total_volume',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
