# Generated by Django 3.2.3 on 2021-06-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_good_total_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='type',
            field=models.CharField(choices=[('BOX', 'BOX'), ('PALLET', 'PALLET')], default='BOX', max_length=20),
        ),
    ]
