# Generated by Django 3.2.2 on 2021-05-09 20:11

from django.db import migrations

from geo.migrations.init.func import from_json


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(from_json)
    ]
