# Generated by Django 3.2.2 on 2021-05-09 20:11
import sys

from django.conf import settings
from django.db import migrations

from geo.migrations.init import load
from geo.migrations.init.test import load as tes_load


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0001_initial'),
    ]
