# Generated by Django 3.2.2 on 2021-05-09 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20210509_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city'),
        ),
    ]
