# Generated by Django 3.2.2 on 2021-05-09 21:25

from django.db import migrations

from geo.migrations.init.func import set_capital


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_country_capital'),
    ]

    operations = [
        migrations.RunPython(set_capital)
    ]
