# Generated by Django 3.2.2 on 2021-05-09 21:25
from django.conf import settings
from django.db import migrations

from geo.migrations.init.load import set_capital


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_country_capital'),
    ]

    operations = [
        migrations.RunPython(set_capital)
    ] if not settings.TEST_RUN else []
