# Generated by Django 3.2.3 on 2021-07-08 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0006_auto_20210512_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='zone',
        ),
        migrations.AddField(
            model_name='state',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.zone'),
        ),
    ]
