# Generated by Django 3.2.3 on 2021-07-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0009_city_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='alias_en',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='alias_ru',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='alias_en',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='alias_ru',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='alias_en',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='state',
            name='alias_ru',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
