# Generated by Django 3.2.3 on 2021-07-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_auto_20210720_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='capital',
        ),
    ]
