# Generated by Django 3.2.3 on 2021-06-28 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0015_alter_routetimetable_weekdays'),
        ('goods', '0003_auto_20210628_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=250)),
                ('index', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=500)),
                ('contact_person', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_by_consignee', to='order.orderunit')),
                ('good', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='goods.good')),
                ('path', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='route.path')),
                ('shipper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_by_shipper', to='order.orderunit')),
                ('special', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.special')),
            ],
        ),
    ]
