# Generated by Django 3.2.3 on 2021-07-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210715_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='special',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.special'),
        ),
    ]
