# Generated by Django 3.2.3 on 2021-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_special'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special',
            name='departure_date',
            field=models.DateField(null=True),
        ),
    ]
