# Generated by Django 3.2.3 on 2021-07-15 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_special_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_stamp',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
