# Generated by Django 3.2.3 on 2021-08-08 00:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_customs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderagent',
            name='address',
        ),
        migrations.RemoveField(
            model_name='orderagent',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='orderagent',
            name='comment',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='special',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
