# Generated by Django 3.2.3 on 2021-08-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210808_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderagent',
            name='company_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderagent',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
