# Generated by Django 3.2.3 on 2021-08-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20210807_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='special',
            name='send_mail',
            field=models.BooleanField(default=False),
        ),
    ]
